# Generated by Django 6.0 on 2025-12-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_announcement_contactinfo_doctor_homeslide_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslide',
            options={'ordering': ['order'], 'verbose_name': 'Home Slide', 'verbose_name_plural': 'Home Slides'},
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='image',
            field=models.ImageField(upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this slide'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower number = appears first'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
