# Generated by Django 6.0 on 2025-12-28 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_homeslide_options_alter_homeslide_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 28, 7, 28, 56, 805183, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='button_url',
            field=models.CharField(blank=True, default='/contact/', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to show this announcement'),
        ),
    ]
