# Generated by Django 6.0 on 2025-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_alter_announcement_options_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(help_text='Background image for the hero section', upload_to='about/')),
                ('story_image', models.ImageField(help_text="Image next to 'Our Story' section", upload_to='about/')),
                ('story_title', models.CharField(default='Our Story', max_length=200)),
                ('story_content', models.TextField(help_text='The main story text for the About page')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
